# These are supported funding model platforms

github: [skunkworksza, another_username] # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: skunkworksza_patreon # Replace with a single Patreon username
open_collective: skunkworksza_collective # Replace with a single Open Collective username
ko_fi: skunkworksza_kofi # Replace with a single Ko-fi username
tidelift: npm/skunkworksza_package # Replace with a single Tidelift platform-name/package-name
community_bridge: skunkworksza_project # Replace with a single Community Bridge project-name
liberapay: skunkworksza_libera # Replace with a single Liberapay username
issuehunt: skunkworksza_issuehunt # Replace with a single IssueHunt username
otechie: skunkworksza_ot # Replace with a single Otechie username
lfx_crowdfunding: skunkworksza_crowdfunding # Replace with a single LFX Crowdfunding project-name
custom: ['https://www.customlink1.com', 'https://www.customlink2.com'] # Replace with up to 4 custom sponsorship URLs
